services:
  db:
    image: mysql:9
    ports:
    - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "human_resource"
      MYSQL_DATABASE: "human_resource"
  redis:
    image: redis:7
    ports: 
    - "6379:6379"